import subprocess
import sys
from pathlib import Path
import pandas as pd
import time


# ============================================================
# AURA v0.3 — MULTI-SYMBOL HISTORICAL SIGNAL SCANNER
# ============================================================
#
# Research only.
# NO ORDERS ARE PLACED.
#
# This wrapper deliberately calls the already-tested
# historical_signal_scanner.py rather than duplicating
# its signal logic.
#
# Outputs:
#   research/multi_symbol_historical_signals.csv
#   research/multi_symbol_signal_summary.csv
# ============================================================


START_DATE = "2026-01-01"
END_DATE = "2026-08-25"

SYMBOLS = [
    # Technology
    "AAPL",
    "MSFT",
    "NVDA",
    "AMZN",
    "GOOGL",
    "META",
    "AVGO",

    # Consumer / EV
    "TSLA",
    "WMT",
    "COST",

    # Financials
    "JPM",
    "BAC",
    "GS",

    # Energy
    "XOM",
    "CVX",

    # Industrials / materials
    "CAT",
    "DE",
    "GE",

    # Defense
    "LMT",
    "RTX",

    # Healthcare
    "LLY",
    "JNJ",

    # Market / commodity proxies
    "SPY",
    "QQQ",
    "IWM",
    "GLD",
    "SLV",
]


ROOT = Path(__file__).resolve().parent
RESEARCH_DIR = ROOT / "research"

SCANNER = ROOT / "historical_signal_scanner.py"

COMBINED_OUTPUT = RESEARCH_DIR / "multi_symbol_historical_signals.csv"
SUMMARY_OUTPUT = RESEARCH_DIR / "multi_symbol_signal_summary.csv"


def run_scanner(symbol: str) -> bool:
    """Run the existing single-symbol scanner."""

    print()
    print("=" * 70)
    print(f"AURA v0.3 → SCANNING {symbol}")
    print("=" * 70)

    command = [
        sys.executable,
        str(SCANNER),
        "--symbol",
        symbol,
        "--start",
        START_DATE,
        "--end",
        END_DATE,
    ]

    try:
        result = subprocess.run(
            command,
            cwd=ROOT,
            text=True,
            capture_output=True,
        )

        # Display scanner output so we can see what happened.
        if result.stdout:
            print(result.stdout)

        if result.stderr:
            print("STDERR:")
            print(result.stderr)

        if result.returncode != 0:
            print(f"❌ {symbol}: scanner failed")
            return False

        return True

    except Exception as exc:
        print(f"❌ {symbol}: exception: {exc}")
        return False


def find_symbol_csv(symbol: str):
    """Find the CSV generated by the single-symbol scanner."""

    expected = RESEARCH_DIR / f"{symbol.lower()}_historical_signals.csv"

    if expected.exists():
        return expected

    # Fallback search in case the scanner uses another case.
    matches = list(
        RESEARCH_DIR.glob(f"*{symbol.lower()}*historical*signals*.csv")
    )

    if matches:
        return matches[0]

    return None


def load_symbol_results(symbol: str):
    """Load one symbol's historical signal results."""

    csv_path = find_symbol_csv(symbol)

    if csv_path is None:
        print(f"⚠️  {symbol}: no signal CSV produced")
        return None

    try:
        df = pd.read_csv(csv_path)

        if df.empty:
            print(f"⚠️  {symbol}: CSV exists but contains no rows")
            return None

        # Guarantee a symbol column.
        if "symbol" not in df.columns:
            df.insert(0, "symbol", symbol)
        else:
            df["symbol"] = symbol

        return df

    except Exception as exc:
        print(f"❌ {symbol}: unable to read {csv_path}")
        print(exc)
        return None


def build_summary(all_results: pd.DataFrame) -> pd.DataFrame:
    """Build a compact performance summary by symbol."""

    rows = []

    for symbol, group in all_results.groupby("symbol"):
        row = {
            "symbol": symbol,
            "signals": len(group),
        }

        # Forward return statistics.
        for col in [
            "forward_1d",
            "forward_3d",
            "forward_5d",
            "forward_10d",
            "mfe_5d",
            "mae_5d",
        ]:
            if col in group.columns:
                values = pd.to_numeric(
                    group[col],
                    errors="coerce",
                )

                row[f"{col}_mean"] = values.mean()
                row[f"{col}_median"] = values.median()

        # Outcome distribution.
        if "outcome" in group.columns:
            outcomes = group["outcome"].fillna("UNKNOWN")

            row["positive"] = int(
                (outcomes == "POSITIVE").sum()
            )

            row["strong_positive"] = int(
                (outcomes == "STRONG_POSITIVE").sum()
            )

            row["flat"] = int(
                (outcomes == "FLAT").sum()
            )

            row["negative"] = int(
                (outcomes == "NEGATIVE").sum()
            )

            row["positive_rate"] = (
                (row["positive"] + row["strong_positive"])
                / row["signals"]
                if row["signals"]
                else 0
            )

        rows.append(row)

    return pd.DataFrame(rows)


def main():

    print()
    print("=" * 70)
    print("AURA v0.3 — MULTI-SYMBOL HISTORICAL SIGNAL SCANNER")
    print("=" * 70)
    print(f"Period: {START_DATE} -> {END_DATE}")
    print(f"Symbols: {len(SYMBOLS)}")
    print("MODE: RESEARCH ONLY — NO ORDERS")
    print()

    if not SCANNER.exists():
        print("❌ historical_signal_scanner.py was not found.")
        print(f"Expected: {SCANNER}")
        sys.exit(1)

    RESEARCH_DIR.mkdir(exist_ok=True)

    successful = []
    failed = []
    results = []

    for symbol in SYMBOLS:

        ok = run_scanner(symbol)

        if not ok:
            failed.append(symbol)
            continue

        successful.append(symbol)

        # Give the filesystem a moment to flush the CSV.
        time.sleep(0.2)

        df = load_symbol_results(symbol)

        if df is not None:
            results.append(df)

    print()
    print("=" * 70)
    print("AURA v0.3 — AGGREGATING RESULTS")
    print("=" * 70)

    if not results:
        print("❌ No historical signal results were produced.")
        sys.exit(1)

    combined = pd.concat(
        results,
        ignore_index=True,
    )

    combined.to_csv(
        COMBINED_OUTPUT,
        index=False,
    )

    summary = build_summary(combined)

    if not summary.empty:
        summary = summary.sort_values(
            by="positive_rate",
            ascending=False,
        )

    summary.to_csv(
        SUMMARY_OUTPUT,
        index=False,
    )

    print()
    print(f"Symbols successfully scanned: {len(successful)}")
    print(f"Symbols failed: {len(failed)}")
    print(f"Total historical signals: {len(combined)}")
    print()
    print(f"Combined CSV:")
    print(COMBINED_OUTPUT)
    print()
    print(f"Summary CSV:")
    print(SUMMARY_OUTPUT)

    if failed:
        print()
        print("Failed symbols:")
        print(", ".join(failed))

    print()
    print("=" * 70)
    print("AURA v0.3 MULTI-SYMBOL SCAN COMPLETE")
    print("NO ORDERS WERE PLACED")
    print("=" * 70)


if __name__ == "__main__":
    main()