#!/usr/bin/env python3
"""
AURA v0.5.3.18 — Reconciliation

LOCKED ARCHITECTURE
-------------------
Consumes ONLY:
    1. the authenticated v0.5.3.17 Decision / Execution Ledger; and
    2. an explicit observed-execution snapshot supplied to this module.

This layer deliberately does NOT:
- fetch market data;
- calculate indicators;
- recalculate signals or risk;
- size positions;
- create positions;
- place orders;
- call MEXC or any exchange;
- fabricate fills, prices, timestamps, or positions;
- convert an order intent into an observed fill without evidence.

Its responsibility is to reconcile an execution INTENT/RECORD against an
explicit OBSERVED EXECUTION source. The observed source is data, not an
execution authority. Missing or inconsistent observation data fails closed.

Important distinction:
    PAPER_ORDER_INTENT + OBSERVED_FILL -> RECONCILED_EXECUTION
    PAPER_ORDER_INTENT alone            -> UNRECONCILED
    NO_ORDER + no observation           -> UNVERIFIED

Default inputs:
    regime_output/decision_execution_ledger/decision_execution_ledger.json
    regime_input/observed_execution/observed_execution.json

Default output:
    regime_output/reconciliation/reconciliation.json

The default observed-execution file is intentionally NOT generated by this
module. AURA must never manufacture its own evidence of execution.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path
from typing import Any

VERSION = "AURA v0.5.3.18"
EXPECTED_SOURCE_VERSION = "AURA v0.5.3.17"
EXPECTED_SOURCE_ENGINE = "DECISION_EXECUTION_LEDGER"
EXPECTED_OBSERVED_ENGINE = "OBSERVED_EXECUTION"

DEFAULT_LEDGER_INPUT = Path(
    r"regime_output\decision_execution_ledger\decision_execution_ledger.json"
)
DEFAULT_OBSERVED_INPUT = Path(
    r"regime_input\observed_execution\observed_execution.json"
)
DEFAULT_OUTPUT = Path(
    r"regime_output\reconciliation\reconciliation.json"
)
SYMBOLS = ("BTC/USD", "ETH/USD")
REQUIRED_SYMBOLS = SYMBOLS  # BTC/ETH remain the only symbols that can ever
# block the whole reconciliation decision if missing/invalid, or gate the
# overall_reconciliation aggregate to CONFLICT. Kept as a separate name
# (aliased to SYMBOLS) so the rest of this file reads unambiguously --
# mirrors the same alias in v0.5.3.13-.17.
ALLOWED_LEDGER_EVENTS = {
    "NO_ORDER_RECORDED",
    "PAPER_ORDER_INTENT_RECORDED",
}
ALLOWED_OBSERVED_STATUSES = {
    "FILLED",
    "PARTIALLY_FILLED",
    "REJECTED",
    "CANCELED",
    "PENDING",
}


def stable_json(obj: Any) -> str:
    return json.dumps(
        obj,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
        allow_nan=False,
    )


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def load_json(path: Path) -> dict[str, Any]:
    if not path.exists():
        raise FileNotFoundError(f"Input file not found: {path}")
    with path.open("r", encoding="utf-8") as f:
        payload = json.load(f)
    if not isinstance(payload, dict):
        raise ValueError("Input JSON must contain an object at the top level.")
    return payload


def base_result(ledger_path: Path, observed_path: Path) -> dict[str, Any]:
    return {
        "agent_version": VERSION,
        "engine": "RECONCILIATION",
        "decision_status": "BLOCKED",
        "overall_reconciliation": "BLOCKED",
        "generated_from_ledger": str(ledger_path.resolve()),
        "generated_from_observed_execution": str(observed_path.resolve()),
        "input_ledger_hash": None,
        "input_observed_execution_hash": None,
        "upstream_state_id": None,
        "upstream_hash_verified": False,
        "frozen_configuration_verified": False,
        "observed_execution_verified": False,
        "decisions": {},
        "blocked_reasons": [],
        "state_hash": None,
        "state_id": None,
        "guardrails": {
            "single_source_of_truth": True,
            "source_engine": EXPECTED_SOURCE_VERSION,
            "market_data_fetch": False,
            "indicator_recalculation": False,
            "signal_recalculation": False,
            "risk_recalculation": False,
            "position_sizing": False,
            "position_creation": False,
            "exchange_state_mutation": False,
            "orders_allowed": False,
            "paper_execution": False,
            "live_execution": False,
            "reconciliation_only": True,
            "position_creation_from_observation": False,
            "fabricated_fill": False,
            "fabricated_position": False,
            "fail_closed": True,
        },
    }


def canonical_ledger_hash(payload: dict[str, Any]) -> str:
    canonical = {
        "agent_version": payload.get("agent_version"),
        "engine": payload.get("engine"),
        "decision_status": payload.get("decision_status"),
        "overall_ledger_decision": payload.get("overall_ledger_decision"),
        "input_paper_execution_hash": payload.get("input_paper_execution_hash"),
        "upstream_state_id": payload.get("upstream_state_id"),
        "upstream_hash_verified": payload.get("upstream_hash_verified"),
        "frozen_configuration_verified": payload.get("frozen_configuration_verified"),
        "ledger_entries": payload.get("ledger_entries"),
        "blocked_reasons": payload.get("blocked_reasons"),
    }
    return sha256_text(stable_json(canonical))


def canonical_observed_hash(payload: dict[str, Any]) -> str:
    canonical = {
        "agent_version": payload.get("agent_version"),
        "engine": payload.get("engine"),
        "snapshot_status": payload.get("snapshot_status"),
        "observations": payload.get("observations"),
    }
    return sha256_text(stable_json(canonical))


def ledger_entry_reconciliation_errors_for_symbol(symbol: str, item: Any) -> list[str]:
    """
    Structural validity check for a single symbol's v0.5.3.17 ledger entry,
    from reconciliation's point of view. No ledger state is recalculated
    here. Note ALLOWED_LEDGER_EVENTS deliberately excludes "BLOCKED": a
    symbol v0.5.3.17 itself already blocked has nothing to reconcile, and
    naturally falls out as invalid here too (reported per-symbol, never
    globally, for an optional symbol).
    """
    if not isinstance(item, dict):
        return [f"MISSING_OR_INVALID_SYMBOL:{symbol}"]

    errors: list[str] = []
    event = item.get("ledger_event")
    if event not in ALLOWED_LEDGER_EVENTS:
        errors.append(f"INVALID_LEDGER_EVENT:{symbol}:{event!r}")
    if item.get("position_exists") is not False:
        errors.append(f"POSITION_CLAIM_NOT_FALSE:{symbol}")
    if item.get("position_id") is not None:
        errors.append(f"POSITION_ID_PRESENT:{symbol}")
    if item.get("fill_price") is not None:
        errors.append(f"FILL_PRICE_PRESENT_IN_LEDGER:{symbol}")
    if item.get("fill_timestamp") is not None:
        errors.append(f"FILL_TIMESTAMP_PRESENT_IN_LEDGER:{symbol}")

    return errors


def observation_errors_for_symbol(symbol: str, item: Any) -> list[str]:
    """
    Structural validity check for a single symbol's observed-execution
    entry. No observation is fabricated or recalculated here.
    """
    if not isinstance(item, dict):
        return [f"MISSING_OR_INVALID_OBSERVATION:{symbol}"]

    errors: list[str] = []
    status = item.get("order_status")
    if status not in ALLOWED_OBSERVED_STATUSES:
        errors.append(f"INVALID_OBSERVED_ORDER_STATUS:{symbol}:{status!r}")

    position_exists = item.get("position_exists")
    if not isinstance(position_exists, bool):
        errors.append(f"INVALID_OBSERVED_POSITION_EXISTS:{symbol}")

    position_id = item.get("position_id")
    fill_price = item.get("fill_price")
    fill_timestamp = item.get("fill_timestamp")

    if position_exists is True and not isinstance(position_id, str):
        errors.append(f"OBSERVED_POSITION_ID_REQUIRED:{symbol}")
    if position_exists is False and position_id is not None:
        errors.append(f"OBSERVED_POSITION_ID_WITHOUT_POSITION:{symbol}")

    if status in {"FILLED", "PARTIALLY_FILLED"}:
        if not isinstance(fill_price, (int, float)) or isinstance(fill_price, bool) or fill_price <= 0:
            errors.append(f"OBSERVED_FILL_PRICE_REQUIRED:{symbol}")
        if not isinstance(fill_timestamp, str) or not fill_timestamp:
            errors.append(f"OBSERVED_FILL_TIMESTAMP_REQUIRED:{symbol}")
    else:
        if fill_price is not None or fill_timestamp is not None:
            errors.append(f"OBSERVED_FILL_PRESENT_FOR_NONFILL:{symbol}")

    return errors


def verify_ledger(payload: dict[str, Any]) -> tuple[bool, list[str]]:
    errors: list[str] = []

    if payload.get("engine") != EXPECTED_SOURCE_ENGINE:
        errors.append("WRONG_UPSTREAM_ENGINE")
    if payload.get("agent_version") != EXPECTED_SOURCE_VERSION:
        errors.append("WRONG_UPSTREAM_VERSION")
    if payload.get("decision_status") != "DECIDED":
        errors.append("UPSTREAM_NOT_DECIDED")

    supplied_hash = payload.get("state_hash")
    if not isinstance(supplied_hash, str) or not supplied_hash:
        errors.append("MISSING_UPSTREAM_STATE_HASH")
    else:
        try:
            calculated = canonical_ledger_hash(payload)
        except (TypeError, ValueError):
            errors.append("UPSTREAM_STATE_NOT_HASHABLE")
        else:
            if calculated != supplied_hash:
                errors.append("UPSTREAM_STATE_HASH_MISMATCH")
        if payload.get("state_id") != f"LE-{supplied_hash[:24]}":
            errors.append("UPSTREAM_STATE_ID_MISMATCH")

    if payload.get("upstream_hash_verified") is not True:
        errors.append("UPSTREAM_HASH_NOT_VERIFIED")
    if payload.get("frozen_configuration_verified") is not True:
        errors.append("UPSTREAM_CONFIGURATION_NOT_VERIFIED")
    if not isinstance(payload.get("upstream_state_id"), str) or not payload.get(
        "upstream_state_id"
    ):
        errors.append("MISSING_UPSTREAM_STATE_ID")

    guardrails = payload.get("guardrails")
    if not isinstance(guardrails, dict):
        errors.append("MISSING_UPSTREAM_GUARDRAILS")
    else:
        if guardrails.get("single_source_of_truth") is not True:
            errors.append("UPSTREAM_SST_NOT_ENFORCED")
        expected_false = (
            "market_data_fetch", "indicator_recalculation", "signal_recalculation",
            "risk_recalculation", "position_sizing", "position_creation",
            "exchange_state_mutation", "orders_allowed", "paper_execution",
            "live_execution", "ledger_authorization", "ledger_state_mutation",
            "position_claim_from_ledger",
        )
        for key in expected_false:
            if guardrails.get(key) is not False:
                errors.append(f"UPSTREAM_GUARDRAIL_VIOLATION:{key}")

    entries = payload.get("ledger_entries")
    if not isinstance(entries, dict):
        errors.append("MISSING_UPSTREAM_LEDGER_ENTRIES")
        return False, sorted(set(errors))

    # Only REQUIRED_SYMBOLS (BTC/ETH) gate the whole decision here. Every
    # other symbol v0.5.3.17 reports is validated independently, per-symbol,
    # in build_reconciliation() below.
    for symbol in REQUIRED_SYMBOLS:
        errors.extend(
            ledger_entry_reconciliation_errors_for_symbol(symbol, entries.get(symbol))
        )

    return len(errors) == 0, sorted(set(errors))


def verify_observed(payload: dict[str, Any]) -> tuple[bool, list[str]]:
    errors: list[str] = []

    if payload.get("engine") != EXPECTED_OBSERVED_ENGINE:
        errors.append("WRONG_OBSERVED_ENGINE")
    if payload.get("snapshot_status") != "OBSERVED":
        errors.append("OBSERVED_SNAPSHOT_NOT_MARKED_OBSERVED")

    supplied_hash = payload.get("snapshot_hash")
    if not isinstance(supplied_hash, str) or not supplied_hash:
        errors.append("MISSING_OBSERVED_SNAPSHOT_HASH")
    else:
        try:
            calculated = canonical_observed_hash(payload)
        except (TypeError, ValueError):
            errors.append("OBSERVED_SNAPSHOT_NOT_HASHABLE")
        else:
            if calculated != supplied_hash:
                errors.append("OBSERVED_SNAPSHOT_HASH_MISMATCH")

    observations = payload.get("observations")
    if not isinstance(observations, dict):
        errors.append("MISSING_OBSERVATIONS")
        return False, sorted(set(errors))

    # Only REQUIRED_SYMBOLS (BTC/ETH) gate the whole decision here. Every
    # other symbol's observation is validated independently, per-symbol, in
    # build_reconciliation() below.
    for symbol in REQUIRED_SYMBOLS:
        errors.extend(observation_errors_for_symbol(symbol, observations.get(symbol)))

    return len(errors) == 0, sorted(set(errors))


def reconcile_symbol(symbol: str, entry: dict[str, Any], obs: dict[str, Any]) -> tuple[dict[str, Any], str]:
    """
    Reconcile one symbol's already-validated ledger entry against its
    already-validated observation. No execution or fill is fabricated
    here -- every branch either confirms/reconciles with data the caller
    supplied, or flags a conflict/pending state. Returns the decision dict
    plus its reconciliation_state, so callers can bucket required-vs-
    optional symbols identically without duplicating this logic.
    """
    ledger_event = entry["ledger_event"]
    status = obs["order_status"]
    observed_position = obs["position_exists"]

    if ledger_event == "NO_ORDER_RECORDED":
        if observed_position or status in {"FILLED", "PARTIALLY_FILLED", "PENDING"}:
            state = "RECONCILIATION_CONFLICT"
            reason = "OBSERVED_EXECUTION_WITHOUT_LEDGER_ORDER"
            execution_reconciled = False
            position_exists = False
            position_id = None
            fill_price = None
            fill_timestamp = None
        else:
            state = "NO_ORDER_CONFIRMED"
            reason = "LEDGER_NO_ORDER_AND_NO_OBSERVED_EXECUTION"
            execution_reconciled = True
            position_exists = False
            position_id = None
            fill_price = None
            fill_timestamp = None

    elif ledger_event == "PAPER_ORDER_INTENT_RECORDED":
        if status in {"FILLED", "PARTIALLY_FILLED"}:
            if not observed_position:
                state = "RECONCILIATION_CONFLICT"
                reason = "OBSERVED_FILL_WITHOUT_OBSERVED_POSITION"
                execution_reconciled = False
                position_exists = False
                position_id = None
                fill_price = None
                fill_timestamp = None
            else:
                state = "RECONCILED_EXECUTION"
                reason = "LEDGER_INTENT_MATCHED_OBSERVED_EXECUTION"
                execution_reconciled = True
                position_exists = True
                position_id = obs["position_id"]
                fill_price = obs["fill_price"]
                fill_timestamp = obs["fill_timestamp"]
        elif status in {"PENDING"}:
            state = "EXECUTION_PENDING"
            reason = "LEDGER_INTENT_AWAITING_OBSERVED_EXECUTION"
            execution_reconciled = False
            position_exists = False
            position_id = None
            fill_price = None
            fill_timestamp = None
        elif status in {"REJECTED", "CANCELED"}:
            state = "EXECUTION_NOT_FILLED"
            reason = "LEDGER_INTENT_OBSERVED_NOT_FILLED"
            execution_reconciled = True
            position_exists = False
            position_id = None
            fill_price = None
            fill_timestamp = None
        else:
            state = "RECONCILIATION_CONFLICT"
            reason = "UNSUPPORTED_INTENT_OBSERVATION_COMBINATION"
            execution_reconciled = False
            position_exists = False
            position_id = None
            fill_price = None
            fill_timestamp = None
    else:
        state = "RECONCILIATION_CONFLICT"
        reason = "UNEXPECTED_LEDGER_EVENT"
        execution_reconciled = False
        position_exists = False
        position_id = None
        fill_price = None
        fill_timestamp = None

    decision = {
        "symbol": symbol,
        "ledger_event": ledger_event,
        "observed_order_status": status,
        "reconciliation_state": state,
        "execution_reconciled": execution_reconciled,
        "position_exists": position_exists,
        "position_id": position_id,
        "fill_price": fill_price,
        "fill_timestamp": fill_timestamp,
        "reason": reason,
    }
    return decision, state


def build_reconciliation(
    ledger: dict[str, Any],
    observed: dict[str, Any],
    ledger_path: Path,
    observed_path: Path,
) -> dict[str, Any]:
    result = base_result(ledger_path, observed_path)
    result["input_ledger_hash"] = ledger.get("state_hash")
    result["input_observed_execution_hash"] = observed.get("snapshot_hash")
    result["upstream_state_id"] = ledger.get("state_id")
    result["upstream_hash_verified"] = ledger.get("upstream_hash_verified") is True
    result["frozen_configuration_verified"] = ledger.get("frozen_configuration_verified") is True

    ledger_ok, ledger_errors = verify_ledger(ledger)
    observed_ok, observed_errors = verify_observed(observed)

    if not ledger_ok or not observed_ok:
        result["blocked_reasons"] = sorted(set(ledger_errors + observed_errors))
        # Envelope-level failure -- scoped to REQUIRED_SYMBOLS only, same as
        # the global gates that produced it.
        for symbol in REQUIRED_SYMBOLS:
            result["decisions"][symbol] = {
                "symbol": symbol,
                "ledger_event": None,
                "observed_order_status": None,
                "reconciliation_state": "BLOCKED",
                "execution_reconciled": False,
                "position_exists": False,
                "position_id": None,
                "fill_price": None,
                "fill_timestamp": None,
                "reason": "INPUT_VALIDATION_FAILED",
            }
        return finalize(result)

    result["observed_execution_verified"] = True
    ledger_entries = ledger["ledger_entries"]
    observations = observed["observations"]

    reconciled_count = 0
    pending_count = 0
    required_conflict_count = 0
    optional_blocked_symbols: list[str] = []

    # Every symbol reported by either upstream source gets reconciled;
    # REQUIRED_SYMBOLS are added even if somehow absent (verify_ledger/
    # verify_observed already gated a truly missing/invalid required
    # symbol above, so this is just defensive). Mirrors the required-vs-
    # optional pattern already shipped in v0.5.3.12-.17.
    selected = sorted(
        set(ledger_entries.keys()) | set(observations.keys()) | set(REQUIRED_SYMBOLS)
    )

    for symbol in selected:
        is_required = symbol in REQUIRED_SYMBOLS
        entry = ledger_entries.get(symbol)
        obs = observations.get(symbol)

        if not is_required:
            # Both sides were already verified for REQUIRED_SYMBOLS as a
            # global gate above; an optional symbol's ledger entry and
            # observation were not checked yet -- do it here so one
            # optional symbol's bad/missing data never blocks another
            # symbol's reconciliation. Consistent with this file's own
            # fail-closed philosophy: a missing observation is never
            # silently treated as reconciled, even for an optional symbol.
            entry_errors = ledger_entry_reconciliation_errors_for_symbol(symbol, entry)
            obs_errors = observation_errors_for_symbol(symbol, obs)
            if entry_errors or obs_errors:
                result["decisions"][symbol] = {
                    "symbol": symbol,
                    "ledger_event": entry.get("ledger_event") if isinstance(entry, dict) else None,
                    "observed_order_status": obs.get("order_status") if isinstance(obs, dict) else None,
                    "reconciliation_state": "BLOCKED",
                    "execution_reconciled": False,
                    "position_exists": False,
                    "position_id": None,
                    "fill_price": None,
                    "fill_timestamp": None,
                    "reason": "OPTIONAL_SYMBOL_INPUT_VALIDATION_FAILED",
                }
                optional_blocked_symbols.append(symbol)
                continue

        decision, state = reconcile_symbol(symbol, entry, obs)
        result["decisions"][symbol] = decision

        if state == "RECONCILIATION_CONFLICT":
            if is_required:
                required_conflict_count += 1
            else:
                # An optional symbol's own conflicting evidence blocks only
                # that symbol's reconciliation, never the whole cycle.
                optional_blocked_symbols.append(symbol)
        elif state == "EXECUTION_PENDING":
            pending_count += 1
        else:
            reconciled_count += 1

    if optional_blocked_symbols:
        result["optional_symbols_blocked"] = sorted(set(optional_blocked_symbols))

    result["decision_status"] = "DECIDED"
    if required_conflict_count:
        result["overall_reconciliation"] = "CONFLICT"
    elif pending_count and not reconciled_count:
        result["overall_reconciliation"] = "PENDING"
    elif reconciled_count:
        result["overall_reconciliation"] = "RECONCILED"
    else:
        result["overall_reconciliation"] = "UNVERIFIED"

    return finalize(result)


def finalize(result: dict[str, Any]) -> dict[str, Any]:
    canonical = {
        "agent_version": result["agent_version"],
        "engine": result["engine"],
        "decision_status": result["decision_status"],
        "overall_reconciliation": result["overall_reconciliation"],
        "input_ledger_hash": result["input_ledger_hash"],
        "input_observed_execution_hash": result["input_observed_execution_hash"],
        "upstream_state_id": result["upstream_state_id"],
        "upstream_hash_verified": result["upstream_hash_verified"],
        "frozen_configuration_verified": result["frozen_configuration_verified"],
        "observed_execution_verified": result["observed_execution_verified"],
        "decisions": result["decisions"],
        "blocked_reasons": result["blocked_reasons"],
    }
    result["state_hash"] = sha256_text(stable_json(canonical))
    result["state_id"] = f"RC-{result['state_hash'][:24]}"
    return result


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2, ensure_ascii=False, allow_nan=False)
        f.write("\n")


def print_report(result: dict[str, Any], output_path: Path) -> None:
    print("=" * 96)
    print(f"{VERSION} — RECONCILIATION")
    print("=" * 96)
    print()
    print("MODE                 : RESEARCH ONLY")
    print("ORDERS               : DISABLED")
    print("MEXC / EXCHANGE CALL : DISABLED")
    print("LIVE EXECUTION       : DISABLED")
    print("POSITION CREATION    : DISABLED")
    print("RECONCILIATION ONLY  : ENABLED")
    print("POSITION FABRICATION : DISABLED")
    print()
    print("RECONCILIATION")
    print("-" * 96)
    print(f"STATUS               : {result['decision_status']}")
    print(f"OVERALL RECONCILIATION: {result['overall_reconciliation']}")
    print(f"UPSTREAM STATE ID    : {result['upstream_state_id']}")
    print(f"UPSTREAM HASH VERIFIED: {result['upstream_hash_verified']}")
    print(f"CONFIG VERIFIED      : {result['frozen_configuration_verified']}")
    print(f"OBSERVATION VERIFIED : {result['observed_execution_verified']}")
    print(f"STATE ID             : {result['state_id']}")
    print()

    reported_symbols = sorted(set(result["decisions"].keys()) | set(REQUIRED_SYMBOLS))
    optional_blocked = set(result.get("optional_symbols_blocked", []))

    for symbol in reported_symbols:
        item = result["decisions"].get(symbol)
        label = symbol
        if symbol in REQUIRED_SYMBOLS:
            label += "  [REQUIRED]"
        elif symbol in optional_blocked:
            label += "  [OPTIONAL, BLOCKED -- did not affect overall decision]"
        else:
            label += "  [OPTIONAL]"
        print(label)
        if not item:
            print("  RECONCILIATION     : BLOCKED")
            print()
            continue
        print(f"  LEDGER EVENT       : {item['ledger_event']}")
        print(f"  OBSERVED STATUS    : {item['observed_order_status']}")
        print(f"  RECONCILIATION     : {item['reconciliation_state']}")
        print(f"  EXECUTION RECONCILED: {item['execution_reconciled']}")
        print(f"  POSITION EXISTS    : {item['position_exists']}")
        print(f"  POSITION ID        : {item['position_id']}")
        print(f"  FILL PRICE         : {item['fill_price']}")
        print(f"  FILL TIMESTAMP     : {item['fill_timestamp']}")
        print(f"  REASON             : {item['reason']}")
        print()

    if result["blocked_reasons"]:
        print("FAIL-CLOSED REASONS")
        print("-" * 96)
        for reason in result["blocked_reasons"]:
            print(f"  - {reason}")
        print()

    print(f"OUTPUT               : {output_path.resolve()}")
    print("=" * 96)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--ledger-input", type=Path, default=DEFAULT_LEDGER_INPUT)
    parser.add_argument("--observed-input", type=Path, default=DEFAULT_OBSERVED_INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--once", action="store_true", help="Run once and exit")
    args = parser.parse_args()

    try:
        ledger = load_json(args.ledger_input)

        try:
            observed = load_json(args.observed_input)
        except FileNotFoundError as observed_exc:
            # Missing observation is UNVERIFIED only when the authenticated
            # upstream ledger proves that NO order was recorded for every
            # REQUIRED symbol. Never manufacture execution evidence.
            ledger_ok, ledger_errors = verify_ledger(ledger)

            entries = ledger.get("ledger_entries")
            no_order_only = (
                isinstance(entries, dict)
                and all(
                    isinstance(entries.get(symbol), dict)
                    and entries[symbol].get("ledger_event") == "NO_ORDER_RECORDED"
                    for symbol in REQUIRED_SYMBOLS
                )
            )

            if ledger_ok and no_order_only:
                result = base_result(args.ledger_input, args.observed_input)
                result["input_ledger_hash"] = ledger.get("state_hash")
                result["upstream_state_id"] = ledger.get("state_id")
                result["upstream_hash_verified"] = (
                    ledger.get("upstream_hash_verified") is True
                )
                result["frozen_configuration_verified"] = (
                    ledger.get("frozen_configuration_verified") is True
                )

                result["decision_status"] = "DECIDED"
                result["overall_reconciliation"] = "UNVERIFIED"
                result["observed_execution_verified"] = False

                # Include any optional symbols the ledger reported too --
                # with no observation source at all, every one of them is
                # equally unverifiable, never silently upgraded to reconciled.
                reported_symbols = (
                    sorted(set(entries.keys()) | set(REQUIRED_SYMBOLS))
                    if isinstance(entries, dict)
                    else list(REQUIRED_SYMBOLS)
                )

                for symbol in reported_symbols:
                    item = entries.get(symbol) if isinstance(entries, dict) else None
                    ledger_event = item.get("ledger_event") if isinstance(item, dict) else None
                    reason = (
                        "NO_OBSERVATION_SOURCE_FOR_NO_ORDER"
                        if ledger_event == "NO_ORDER_RECORDED"
                        else "NO_OBSERVATION_SOURCE_AVAILABLE"
                    )
                    result["decisions"][symbol] = {
                        "symbol": symbol,
                        "ledger_event": ledger_event,
                        "observed_order_status": None,
                        "reconciliation_state": "UNVERIFIED",
                        "execution_reconciled": False,
                        "position_exists": False,
                        "position_id": None,
                        "fill_price": None,
                        "fill_timestamp": None,
                        "reason": reason,
                    }

                result = finalize(result)
                write_json(args.output, result)
                print_report(result, args.output)
                return 0

            # An order intent, invalid ledger, or mixed ledger must remain
            # fail-closed when execution evidence is unavailable.
            result = base_result(args.ledger_input, args.observed_input)
            result["input_ledger_hash"] = ledger.get("state_hash")
            result["upstream_state_id"] = ledger.get("state_id")
            result["upstream_hash_verified"] = (
                ledger.get("upstream_hash_verified") is True
            )
            result["frozen_configuration_verified"] = (
                ledger.get("frozen_configuration_verified") is True
            )
            result["blocked_reasons"] = sorted(
                set(
                    ledger_errors
                    + [f"MISSING_OBSERVATION_SOURCE:{observed_exc}"]
                )
            )

            result = finalize(result)
            try:
                write_json(args.output, result)
                print_report(result, args.output)
            except Exception:
                pass

            print(f"FAIL-CLOSED: {observed_exc}", file=sys.stderr)
            return 1

        result = build_reconciliation(
            ledger, observed, args.ledger_input, args.observed_input
        )
        write_json(args.output, result)
        print_report(result, args.output)
        return 0

    except FileNotFoundError as exc:
        result = base_result(args.ledger_input, args.observed_input)
        result["blocked_reasons"] = [f"MISSING_INPUT_SOURCE:{exc}"]
        result = finalize(result)
        try:
            write_json(args.output, result)
            print_report(result, args.output)
        except Exception:
            pass
        print(f"FAIL-CLOSED: {exc}", file=sys.stderr)
        return 1
    except Exception as exc:
        result = base_result(args.ledger_input, args.observed_input)
        result["blocked_reasons"] = [f"UNEXPECTED_ENGINE_ERROR:{type(exc).__name__}"]
        result = finalize(result)
        try:
            write_json(args.output, result)
            print_report(result, args.output)
        except Exception:
            pass
        print(f"FAIL-CLOSED ERROR: {type(exc).__name__}: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
